#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build_tsup() {
  set -x
  rm -rfv dist
  # npm i tsup --no-save on CI/CD (uses esbuild no support of emitDecoratorMetadata)
  tsup src/index.ts --format cjs --target es2020 --dts --sourcemap
  cp -fv README.md package.json dist
}

"$@"
